//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WithNetFramework.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clienti
    {
        public int Clicodice { get; set; }
        public string Cliprenome { get; set; }
        public string Cliragsoc { get; set; }
        public string Cliindirizzo { get; set; }
        public string Clilocalita { get; set; }
        public string Cliprovincia { get; set; }
        public string CliCAP { get; set; }
        public string CliRedazione { get; set; }
        public string Clipostaragsoc { get; set; }
        public string ClipostaIndirizzo { get; set; }
        public string Clipostalocalita { get; set; }
        public string Clipostaprov { get; set; }
        public string ClipostaCAP { get; set; }
        public string Clitelefono { get; set; }
        public string Clifax { get; set; }
        public string CliIVA { get; set; }
        public string CliCF { get; set; }
        public string CliCodDestinatario { get; set; }
        public string Clipagamento { get; set; }
        public string CliBanca { get; set; }
        public string CliPiazza { get; set; }
        public Nullable<float> ClipercIVA { get; set; }
        public Nullable<float> Clipercdiritti { get; set; }
        public Nullable<bool> CliprenomeSN { get; set; }
        public string Clicodfor { get; set; }
        public Nullable<int> cligruppo { get; set; }
        public string CliIBAN { get; set; }
        public string CliLingua { get; set; }
        public string CliValuta { get; set; }
        public string CliNazione { get; set; }
        public string ClipostaNazione { get; set; }
        public string CliSWIFT { get; set; }
        public Nullable<bool> CliInUso { get; set; }
        public string Nomenclatura { get; set; }
        public Nullable<double> TarTruccatore { get; set; }
        public Nullable<double> TarParrucchiere { get; set; }
        public Nullable<double> TarManicurista { get; set; }
        public Nullable<double> TarGroomer { get; set; }
        public string CliEMAIL { get; set; }
        public string GAAttenzione { get; set; }
        public Nullable<bool> GACalcoloIVA { get; set; }
        public string GANote { get; set; }
        public string CliNumDicIntenti { get; set; }
        public Nullable<System.DateTime> CliDataDicIntenti { get; set; }
    }
}
