//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WithNetFramework.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documclienti
    {
        public int DCid { get; set; }
        public Nullable<short> DCnumero { get; set; }
        public string DCnumeroCompleto { get; set; }
        public Nullable<short> DCanno { get; set; }
        public string DCtipo { get; set; }
        public Nullable<System.DateTime> DCdata { get; set; }
        public double DCcliente { get; set; }
        public Nullable<double> DCimponibile { get; set; }
        public Nullable<double> DCspese { get; set; }
        public Nullable<double> DCdiritti { get; set; }
        public Nullable<double> DCIVA { get; set; }
        public Nullable<double> DCtotale { get; set; }
        public string DCdescfat { get; set; }
        public string DCdescspese { get; set; }
        public Nullable<System.DateTime> DCdatapag1 { get; set; }
        public Nullable<System.DateTime> DCdatapag2 { get; set; }
        public Nullable<System.DateTime> DCdatapag3 { get; set; }
        public string DCpagato1 { get; set; }
        public string DCpagato2 { get; set; }
        public string DCpagato3 { get; set; }
        public Nullable<double> DCanticipi { get; set; }
        public Nullable<double> DCdirittiop { get; set; }
        public Nullable<double> DCtrattenute { get; set; }
        public string DCBanca { get; set; }
        public string DCPiazza { get; set; }
        public Nullable<int> DCpercIVA { get; set; }
        public Nullable<int> DCpercdiritti { get; set; }
        public string DCpagam { get; set; }
        public string DCBancagreenapple { get; set; }
        public string DCbuonoOrdine { get; set; }
        public string DCpostaRagSoc { get; set; }
        public string DCpostaIndirizzo { get; set; }
        public string DCpostaLocalita { get; set; }
        public string DCpostaProv { get; set; }
        public string DCpostaCAP { get; set; }
        public Nullable<int> DCnumeroPrestazione { get; set; }
        public Nullable<double> DCspese1 { get; set; }
        public string DCdescspese1 { get; set; }
        public Nullable<double> DCspese2 { get; set; }
        public string DCdescspese2 { get; set; }
        public string DCpostaNazione { get; set; }
        public string DClingua { get; set; }
        public string DCvaluta { get; set; }
        public string DCSWIFT { get; set; }
        public string Nomenclatura { get; set; }
        public Nullable<bool> DCPagata { get; set; }
        public Nullable<double> Cambio { get; set; }
        public Nullable<double> DCSconto { get; set; }
        public Nullable<double> DCScontato { get; set; }
        public string DCnoteCliente { get; set; }
        public Nullable<System.DateTime> CliDataDicIntenti { get; set; }
    }
}
