//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WithNetFramework.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GREEN_SVILUPPOEntities : DbContext
    {
        public GREEN_SVILUPPOEntities()
            : base("name=GREEN_SVILUPPOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clienti> Clienti { get; set; }
        public virtual DbSet<Documclienti> Documclienti { get; set; }
        public virtual DbSet<Prestazioni> Prestazioni { get; set; }
        public virtual DbSet<Servizi> Servizi { get; set; }
        public virtual DbSet<Lista_PrestazioniTipi> Lista_PrestazioniTipi { get; set; }
        public virtual DbSet<Lista_CategoriaServizi> Lista_CategoriaServizi { get; set; }
        public virtual DbSet<Lista_Tiposervizio> Lista_Tiposervizio { get; set; }
    }
}
