//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WithNetFramework.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista_CategoriaServizi
    {
        public int CScodice { get; set; }
        public string CSdescrizione { get; set; }
        public Nullable<int> Posizione { get; set; }
        public Nullable<double> PercCompenso { get; set; }
        public Nullable<bool> FatturaRifferita { get; set; }
    }
}
