//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WithNetFramework.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servizi
    {
        public int SRcodice { get; set; }
        public Nullable<short> SRoperatore { get; set; }
        public Nullable<int> SRcliente { get; set; }
        public string SRcategoria { get; set; }
        public string SRtiposervizio { get; set; }
        public Nullable<double> SRimporto { get; set; }
        public Nullable<double> SRimponibile { get; set; }
        public Nullable<double> SRdiritti { get; set; }
        public Nullable<double> SRanticipi { get; set; }
        public Nullable<double> SRtrattenute { get; set; }
        public Nullable<short> SRfatturacli { get; set; }
        public string SRfatturafor { get; set; }
        public Nullable<System.DateTime> SRdatafatturacli { get; set; }
        public Nullable<System.DateTime> SRdatafatturafor { get; set; }
        public bool SRfatturare { get; set; }
        public bool SRfatturato { get; set; }
        public Nullable<int> SRnumgiorni { get; set; }
        public Nullable<int> SRnumeroprestazione { get; set; }
        public string SRfatclianno { get; set; }
        public Nullable<double> SRanticipige { get; set; }
        public bool SRpagato { get; set; }
        public Nullable<System.DateTime> SRdatainizio { get; set; }
        public Nullable<System.DateTime> SRdatafine { get; set; }
        public Nullable<double> SRimportoLordo { get; set; }
        public Nullable<double> SRpctDiritti { get; set; }
        public string SRdescSpese { get; set; }
        public Nullable<double> SRspese { get; set; }
        public Nullable<double> SRspeseGA { get; set; }
        public string SRdescSpese1 { get; set; }
        public Nullable<double> SRspese1 { get; set; }
        public Nullable<double> SRspeseGA1 { get; set; }
        public string SRdescSpese2 { get; set; }
        public Nullable<double> SRspese2 { get; set; }
        public Nullable<double> SRspeseGA2 { get; set; }
        public Nullable<short> SRAnnoFatt { get; set; }
        public Nullable<short> SRMeseFatt { get; set; }
        public bool SResenzioneIvaArt15 { get; set; }
        public Nullable<double> SRpctRivPrev { get; set; }
        public Nullable<double> SRpctIVA { get; set; }
        public Nullable<double> SRpctRitAcc { get; set; }
        public Nullable<double> SRimportoRedazionale { get; set; }
        public Nullable<double> SRimportoOvertime { get; set; }
        public string SRdescSpeseGA { get; set; }
        public string SRdescSpeseGA1 { get; set; }
        public string SRdescSpeseGA2 { get; set; }
        public Nullable<double> SRimportoOvertimeGA { get; set; }
        public Nullable<double> SRImportoGA { get; set; }
        public Nullable<double> SRCompensoAggiunto { get; set; }


        //To eliminate if using entity
        public string CategoriaDesc { get; set; }
        public string TipoSvcDesc { get; set; }
    }
}
