//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace FatturaElettronicaSemplificata
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("FatturaElettronicaSemplificata", Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0", IsNullable = false)]
    public partial class FatturaElettronicaType
    {

        private FatturaElettronicaHeaderType fatturaElettronicaHeaderField;

        private FatturaElettronicaBodyType[] fatturaElettronicaBodyField;

        private FormatoTrasmissioneType versioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FatturaElettronicaHeaderType FatturaElettronicaHeader
        {
            get
            {
                return this.fatturaElettronicaHeaderField;
            }
            set
            {
                this.fatturaElettronicaHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FatturaElettronicaBody", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FatturaElettronicaBodyType[] FatturaElettronicaBody
        {
            get
            {
                return this.fatturaElettronicaBodyField;
            }
            set
            {
                this.fatturaElettronicaBodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FormatoTrasmissioneType versione
        {
            get
            {
                return this.versioneField;
            }
            set
            {
                this.versioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class FatturaElettronicaHeaderType
    {

        private DatiTrasmissioneType datiTrasmissioneField;

        private CedentePrestatoreType cedentePrestatoreField;

        private CessionarioCommittenteType cessionarioCommittenteField;

        private SoggettoEmittenteType soggettoEmittenteField;

        private bool soggettoEmittenteFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatiTrasmissioneType DatiTrasmissione
        {
            get
            {
                return this.datiTrasmissioneField;
            }
            set
            {
                this.datiTrasmissioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CedentePrestatoreType CedentePrestatore
        {
            get
            {
                return this.cedentePrestatoreField;
            }
            set
            {
                this.cedentePrestatoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CessionarioCommittenteType CessionarioCommittente
        {
            get
            {
                return this.cessionarioCommittenteField;
            }
            set
            {
                this.cessionarioCommittenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoggettoEmittenteType SoggettoEmittente
        {
            get
            {
                return this.soggettoEmittenteField;
            }
            set
            {
                this.soggettoEmittenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SoggettoEmittenteSpecified
        {
            get
            {
                return this.soggettoEmittenteFieldSpecified;
            }
            set
            {
                this.soggettoEmittenteFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class DatiTrasmissioneType
    {

        private IdFiscaleType idTrasmittenteField;

        private string progressivoInvioField;

        private FormatoTrasmissioneType formatoTrasmissioneField;

        private string codiceDestinatarioField;

        private string pECDestinatarioField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IdFiscaleType IdTrasmittente
        {
            get
            {
                return this.idTrasmittenteField;
            }
            set
            {
                this.idTrasmittenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string ProgressivoInvio
        {
            get
            {
                return this.progressivoInvioField;
            }
            set
            {
                this.progressivoInvioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FormatoTrasmissioneType FormatoTrasmissione
        {
            get
            {
                return this.formatoTrasmissioneField;
            }
            set
            {
                this.formatoTrasmissioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodiceDestinatario
        {
            get
            {
                return this.codiceDestinatarioField;
            }
            set
            {
                this.codiceDestinatarioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PECDestinatario
        {
            get
            {
                return this.pECDestinatarioField;
            }
            set
            {
                this.pECDestinatarioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class IdFiscaleType
    {

        private string idPaeseField;

        private string idCodiceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdPaese
        {
            get
            {
                return this.idPaeseField;
            }
            set
            {
                this.idPaeseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdCodice
        {
            get
            {
                return this.idCodiceField;
            }
            set
            {
                this.idCodiceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class AllegatiType
    {

        private string nomeAttachmentField;

        private string algoritmoCompressioneField;

        private string formatoAttachmentField;

        private string descrizioneAttachmentField;

        private byte[] attachmentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string NomeAttachment
        {
            get
            {
                return this.nomeAttachmentField;
            }
            set
            {
                this.nomeAttachmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string AlgoritmoCompressione
        {
            get
            {
                return this.algoritmoCompressioneField;
            }
            set
            {
                this.algoritmoCompressioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string FormatoAttachment
        {
            get
            {
                return this.formatoAttachmentField;
            }
            set
            {
                this.formatoAttachmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string DescrizioneAttachment
        {
            get
            {
                return this.descrizioneAttachmentField;
            }
            set
            {
                this.descrizioneAttachmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary")]
        public byte[] Attachment
        {
            get
            {
                return this.attachmentField;
            }
            set
            {
                this.attachmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class DatiIVAType
    {

        private decimal impostaField;

        private bool impostaFieldSpecified;

        private decimal aliquotaField;

        private bool aliquotaFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Imposta
        {
            get
            {
                return this.impostaField;
            }
            set
            {
                this.impostaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImpostaSpecified
        {
            get
            {
                return this.impostaFieldSpecified;
            }
            set
            {
                this.impostaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Aliquota
        {
            get
            {
                return this.aliquotaField;
            }
            set
            {
                this.aliquotaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AliquotaSpecified
        {
            get
            {
                return this.aliquotaFieldSpecified;
            }
            set
            {
                this.aliquotaFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class DatiBeniServiziType
    {

        private string descrizioneField;

        private decimal importoField;

        private DatiIVAType datiIVAField;

        private NaturaType naturaField;

        private bool naturaFieldSpecified;

        private string riferimentoNormativoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Importo
        {
            get
            {
                return this.importoField;
            }
            set
            {
                this.importoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatiIVAType DatiIVA
        {
            get
            {
                return this.datiIVAField;
            }
            set
            {
                this.datiIVAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public NaturaType Natura
        {
            get
            {
                return this.naturaField;
            }
            set
            {
                this.naturaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NaturaSpecified
        {
            get
            {
                return this.naturaFieldSpecified;
            }
            set
            {
                this.naturaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string RiferimentoNormativo
        {
            get
            {
                return this.riferimentoNormativoField;
            }
            set
            {
                this.riferimentoNormativoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public enum NaturaType
    {

        /// <remarks/>
        N1,

        /// <remarks/>
        N2,

        /// <remarks/>
        N3,

        /// <remarks/>
        N4,

        /// <remarks/>
        N5,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class DatiFatturaRettificataType
    {

        private string numeroFRField;

        private System.DateTime dataFRField;

        private string elementiRettificatiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string NumeroFR
        {
            get
            {
                return this.numeroFRField;
            }
            set
            {
                this.numeroFRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime DataFR
        {
            get
            {
                return this.dataFRField;
            }
            set
            {
                this.dataFRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string ElementiRettificati
        {
            get
            {
                return this.elementiRettificatiField;
            }
            set
            {
                this.elementiRettificatiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class DatiGeneraliDocumentoType
    {

        private TipoDocumentoType tipoDocumentoField;

        private string divisaField;

        private System.DateTime dataField;

        private string numeroField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TipoDocumentoType TipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Divisa
        {
            get
            {
                return this.divisaField;
            }
            set
            {
                this.divisaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string Numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public enum TipoDocumentoType
    {

        /// <remarks/>
        TD07,

        /// <remarks/>
        TD08,

        /// <remarks/>
        TD09,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class DatiGeneraliType
    {

        private DatiGeneraliDocumentoType datiGeneraliDocumentoField;

        private DatiFatturaRettificataType datiFatturaRettificataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatiGeneraliDocumentoType DatiGeneraliDocumento
        {
            get
            {
                return this.datiGeneraliDocumentoField;
            }
            set
            {
                this.datiGeneraliDocumentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatiFatturaRettificataType DatiFatturaRettificata
        {
            get
            {
                return this.datiFatturaRettificataField;
            }
            set
            {
                this.datiFatturaRettificataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class FatturaElettronicaBodyType
    {

        private DatiGeneraliType datiGeneraliField;

        private DatiBeniServiziType[] datiBeniServiziField;

        private AllegatiType[] allegatiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatiGeneraliType DatiGenerali
        {
            get
            {
                return this.datiGeneraliField;
            }
            set
            {
                this.datiGeneraliField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatiBeniServizi", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatiBeniServiziType[] DatiBeniServizi
        {
            get
            {
                return this.datiBeniServiziField;
            }
            set
            {
                this.datiBeniServiziField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Allegati", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AllegatiType[] Allegati
        {
            get
            {
                return this.allegatiField;
            }
            set
            {
                this.allegatiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class AltriDatiIdentificativiType
    {

        private string[] itemsField;

        private ItemsChoiceType2[] itemsElementNameField;

        private IndirizzoType sedeField;

        private IndirizzoType stabileOrganizzazioneField;

        private RappresentanteFiscaleType rappresentanteFiscaleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cognome", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        [System.Xml.Serialization.XmlElementAttribute("Denominazione", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        [System.Xml.Serialization.XmlElementAttribute("Nome", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndirizzoType Sede
        {
            get
            {
                return this.sedeField;
            }
            set
            {
                this.sedeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndirizzoType StabileOrganizzazione
        {
            get
            {
                return this.stabileOrganizzazioneField;
            }
            set
            {
                this.stabileOrganizzazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RappresentanteFiscaleType RappresentanteFiscale
        {
            get
            {
                return this.rappresentanteFiscaleField;
            }
            set
            {
                this.rappresentanteFiscaleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0", IncludeInSchema = false)]
    public enum ItemsChoiceType2
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Cognome")]
        Cognome,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Denominazione")]
        Denominazione,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Nome")]
        Nome,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class IndirizzoType
    {

        private string indirizzoField;

        private string numeroCivicoField;

        private string cAPField;

        private string comuneField;

        private string provinciaField;

        private string nazioneField;

        public IndirizzoType()
        {
            this.nazioneField = "IT";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string Indirizzo
        {
            get
            {
                return this.indirizzoField;
            }
            set
            {
                this.indirizzoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string NumeroCivico
        {
            get
            {
                return this.numeroCivicoField;
            }
            set
            {
                this.numeroCivicoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CAP
        {
            get
            {
                return this.cAPField;
            }
            set
            {
                this.cAPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string Comune
        {
            get
            {
                return this.comuneField;
            }
            set
            {
                this.comuneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nazione
        {
            get
            {
                return this.nazioneField;
            }
            set
            {
                this.nazioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class RappresentanteFiscaleType
    {

        private IdFiscaleType idFiscaleIVAField;

        private string[] itemsField;

        private ItemsChoiceType1[] itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IdFiscaleType IdFiscaleIVA
        {
            get
            {
                return this.idFiscaleIVAField;
            }
            set
            {
                this.idFiscaleIVAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cognome", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        [System.Xml.Serialization.XmlElementAttribute("Denominazione", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        [System.Xml.Serialization.XmlElementAttribute("Nome", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0", IncludeInSchema = false)]
    public enum ItemsChoiceType1
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Cognome")]
        Cognome,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Denominazione")]
        Denominazione,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Nome")]
        Nome,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class IdentificativiFiscaliType
    {

        private IdFiscaleType idFiscaleIVAField;

        private string codiceFiscaleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IdFiscaleType IdFiscaleIVA
        {
            get
            {
                return this.idFiscaleIVAField;
            }
            set
            {
                this.idFiscaleIVAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodiceFiscale
        {
            get
            {
                return this.codiceFiscaleField;
            }
            set
            {
                this.codiceFiscaleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class CessionarioCommittenteType
    {

        private IdentificativiFiscaliType identificativiFiscaliField;

        private AltriDatiIdentificativiType altriDatiIdentificativiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IdentificativiFiscaliType IdentificativiFiscali
        {
            get
            {
                return this.identificativiFiscaliField;
            }
            set
            {
                this.identificativiFiscaliField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AltriDatiIdentificativiType AltriDatiIdentificativi
        {
            get
            {
                return this.altriDatiIdentificativiField;
            }
            set
            {
                this.altriDatiIdentificativiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class IscrizioneREAType
    {

        private string ufficioField;

        private string numeroREAField;

        private decimal capitaleSocialeField;

        private bool capitaleSocialeFieldSpecified;

        private SocioUnicoType socioUnicoField;

        private bool socioUnicoFieldSpecified;

        private StatoLiquidazioneType statoLiquidazioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ufficio
        {
            get
            {
                return this.ufficioField;
            }
            set
            {
                this.ufficioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string NumeroREA
        {
            get
            {
                return this.numeroREAField;
            }
            set
            {
                this.numeroREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CapitaleSociale
        {
            get
            {
                return this.capitaleSocialeField;
            }
            set
            {
                this.capitaleSocialeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CapitaleSocialeSpecified
        {
            get
            {
                return this.capitaleSocialeFieldSpecified;
            }
            set
            {
                this.capitaleSocialeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SocioUnicoType SocioUnico
        {
            get
            {
                return this.socioUnicoField;
            }
            set
            {
                this.socioUnicoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SocioUnicoSpecified
        {
            get
            {
                return this.socioUnicoFieldSpecified;
            }
            set
            {
                this.socioUnicoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StatoLiquidazioneType StatoLiquidazione
        {
            get
            {
                return this.statoLiquidazioneField;
            }
            set
            {
                this.statoLiquidazioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public enum SocioUnicoType
    {

        /// <remarks/>
        SU,

        /// <remarks/>
        SM,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public enum StatoLiquidazioneType
    {

        /// <remarks/>
        LS,

        /// <remarks/>
        LN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public partial class CedentePrestatoreType
    {

        private IdFiscaleType idFiscaleIVAField;

        private string codiceFiscaleField;

        private string[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private IndirizzoType sedeField;

        private IndirizzoType stabileOrganizzazioneField;

        private RappresentanteFiscaleType rappresentanteFiscaleField;

        private IscrizioneREAType iscrizioneREAField;

        private RegimeFiscaleType regimeFiscaleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IdFiscaleType IdFiscaleIVA
        {
            get
            {
                return this.idFiscaleIVAField;
            }
            set
            {
                this.idFiscaleIVAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodiceFiscale
        {
            get
            {
                return this.codiceFiscaleField;
            }
            set
            {
                this.codiceFiscaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cognome", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        [System.Xml.Serialization.XmlElementAttribute("Denominazione", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        [System.Xml.Serialization.XmlElementAttribute("Nome", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndirizzoType Sede
        {
            get
            {
                return this.sedeField;
            }
            set
            {
                this.sedeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IndirizzoType StabileOrganizzazione
        {
            get
            {
                return this.stabileOrganizzazioneField;
            }
            set
            {
                this.stabileOrganizzazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RappresentanteFiscaleType RappresentanteFiscale
        {
            get
            {
                return this.rappresentanteFiscaleField;
            }
            set
            {
                this.rappresentanteFiscaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IscrizioneREAType IscrizioneREA
        {
            get
            {
                return this.iscrizioneREAField;
            }
            set
            {
                this.iscrizioneREAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RegimeFiscaleType RegimeFiscale
        {
            get
            {
                return this.regimeFiscaleField;
            }
            set
            {
                this.regimeFiscaleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Cognome")]
        Cognome,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Denominazione")]
        Denominazione,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Nome")]
        Nome,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public enum RegimeFiscaleType
    {

        /// <remarks/>
        RF01,

        /// <remarks/>
        RF02,

        /// <remarks/>
        RF04,

        /// <remarks/>
        RF05,

        /// <remarks/>
        RF06,

        /// <remarks/>
        RF07,

        /// <remarks/>
        RF08,

        /// <remarks/>
        RF09,

        /// <remarks/>
        RF10,

        /// <remarks/>
        RF11,

        /// <remarks/>
        RF12,

        /// <remarks/>
        RF13,

        /// <remarks/>
        RF14,

        /// <remarks/>
        RF15,

        /// <remarks/>
        RF16,

        /// <remarks/>
        RF17,

        /// <remarks/>
        RF19,

        /// <remarks/>
        RF18,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public enum FormatoTrasmissioneType
    {

        /// <remarks/>
        FSM10,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")]
    public enum SoggettoEmittenteType
    {

        /// <remarks/>
        CC,

        /// <remarks/>
        TZ,
    }
}